### ISSUE TITLE
The [japanese] key in pokedex.json is misspelled.

### ISSUE THREAD

**Issue by kenta-miyamura** [Purukitto/pokemon-data.json#18]
To whom this may concern,

id: 810 (Line is 42784)or later is misspelled.
ok: japanese
ng: japanease

I don't understand project rules, Without making a pull request so I will report it as an issue.

Thanks.

**Comment by Purukitto** [comment]
Thank you for pointing this out! If you would like to, you can make a pull request for the same, as long as there are no conflicts and the changes make sense we will merge it.

Otherwise I will do it myself in a few days time

**Comment by kenta-miyamura** [comment]
Dear Purukitto.
I created a pull request. Please confirm.
#19
