### ISSUE TITLE
Change structure of evolution changes

### ISSUE THREAD

**Issue by Purukitto** [Purukitto/pokemon-data.json#9]
## **Description**
Change the evolution structure in [pokedex.json](https://github.com/Purukitto/pokemon-data.json/blob/master/pokedex.json) so that it is easier for evolution chaining

## **The required structure:**

- In case of un-chained evolutions:

#### From:

```
"evolution": {
    "next": {
        "id": "3",
        "req": "Level 32"
    },
    "prev": {
        "id": "1",
        "req": "Level 16"
    }
}
```

#### To:
```
"evolution": {
    "next": [3, "Level 32"],
    "prev": [1, "Level 16"]
}
```

- In case of chained evolutions:

#### From:

```
"evolution": {
    "next": {
        "id": "45",
        "req": "use Leaf Stone"
    },
    "next2": {
        "id": "182",
        "req": "use Sun Stone"
    },
    "prev": {
        "id": "43",
        "req": "Level 21"
    }
}
```

#### To:
```
"evolution": {
    "next": [
        [45, "use Leaf Stone"][182, "use Sun Stone"]
    ],
    "prev": [43, "Level 21"]
}
```

## **Tasks :**
- [ ] To change the structure of `evolution`

### Comment below if you would like to claim this issue, please do not start working on the issue unless assigned to you explicitly

**Comment by jacobggman** [comment]
can I do that?

**Comment by Purukitto** [comment]
@jacobggman Please check the file in question and let me know if you're comfortable with working with the database of that size (809 entries) also confirm that you have noted and understood the requirement of evolution chaining

**Comment by jacobggman** [comment]
I am comfortable with working with the database of that size and I understood the requirement. I am thinking to make a Python script to do that, commit also the script?

**Comment by Purukitto** [comment]
@jacobggman no need for the script! You can start working on the same!

**Comment by jacobggman** [comment]
In case of chained evolutions:
`[45, "use Leaf Stone"][182, "use Sun Stone"]` It need to be a list, right? You meant `[['45', 'use Leaf Stone'], ['182', 'use Sun Stone']]`?

**Comment by Purukitto** [comment]
@jacobggman the requirement is to be able to find the length ( eg. using `evolution.next.length` = 1 or >1 in case of chaining ) and access these separately (eg. using evolution.next[0] , evolution.next[1])
